<?xml version="1.0" ?>
<!-- 
  Copyright (C) 2020  Rhys Mainwaring

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

<!-- Robot description for a RS750 test rig

    Conventions    
    ROS REP 105 Coordinate Frames for Mobile Platforms
    length      x-axis dimension
    width       y-axis dimension
    depth       z-axis dimension

 -->
<robot name="rs750_test_rig" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find rs750_description)/urdf/rs750_materials.xacro"/>
    <xacro:include filename="$(find rs750_description)/urdf/rs750_inertials.xacro"/>
    <xacro:include filename="$(find rs750_description)/urdf/rs750_anemometer.xacro"/>
    <xacro:include filename="$(find rs750_description)/urdf/rs750_imu.xacro"/>
    <xacro:include filename="$(find rs750_description)/urdf/rs750_magnetic.xacro"/>
    <xacro:include filename="$(find rs750_description)/urdf/rs750_rig.xacro"/>
    <xacro:include filename="$(find rs750_description)/urdf/rs750_test_rig.gazebo"/>

    <!-- Constants for robot dimensions -->
    <xacro:property name="scale" value="3.2" />

    <xacro:property name="base_plate_mass" value="${100 * scale * scale * scale}" />
    <xacro:property name="base_plate_length" value="${0.10 * scale}" />
    <xacro:property name="base_plate_radius" value="${0.50 * scale}" /> 

    <!-- The base link - the reference link for the entire model -->
    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </collision>
        <!-- Remove inertial in base_link:
            [ WARN ] The root link base_link has an inertia specified in the URDF,
            but KDL does not support a root link with an inertia.
            As a workaround, you can add an extra dummy link to your URDF.
        -->
        <!--
        <xacro:solid_cuboid_inertial 
            rpy="0 0 0" xyz="0 0 0"
            mass="0.01"
            x="0.01" y="0.01" z="0.01" />
        -->
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- Deck plate  -->
    <link name="base_plate_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${base_plate_length}" radius="${base_plate_radius}" />
            </geometry>
            <material name="red" />
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${base_plate_length}" radius="${base_plate_radius}" />
            </geometry>
        </collision>
        <xacro:solid_cylinder_inertial 
            rpy="0 0 0" xyz="0 0 0"
            mass="${base_plate_mass}"
            length="${base_plate_length}" radius="${base_plate_radius}" />
    </link>

    <gazebo reference="base_plate_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="base_plate_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 ${base_plate_length/2}"/>
        <parent link="base_link" />
        <child link="base_plate_link" />
    </joint>

    <gazebo reference="base_plate_joint">
    </gazebo>

    <!-- Rig -->
    <xacro:rig base_link="base_link" scale="${scale}" x="0.0" y="0.0" z="${base_plate_length/2}" />

    <!-- Anemometer (mast head) -->
    <xacro:anemometer_link />
    <xacro:anemometer_joint x="0.0" y="0.0" z="${base_plate_length + 4.0}" yaw="0" />

    <!-- IMU  -->
    <xacro:imu_link />
    <xacro:imu_joint x="0.0" y="0.0" z="${base_plate_length}" yaw="0" />

    <!-- Magnetometer  -->
    <xacro:magnetic_link />
    <xacro:magnetic_joint x="0.0" y="0.0" z="${base_plate_length}" yaw="0" />

</robot>